### ISSUE TITLE
why is the constructor of Builder class' modifier 'private'? 

### ISSUE THREAD

**Issue by ddsdggsg** [helospark/SparkBuilderGenerator#14]
why is the constructor of Builder class' modifier 'private'?
or am I using it in a wrong way?
![poiuuuiiii-1](https://cloud.githubusercontent.com/assets/10401795/25516654/5f5f2a70-2c1e-11e7-95d4-9de68f090a0e.png)

what is the normal way to use this?
![poiuuuiiii-2](https://cloud.githubusercontent.com/assets/10401795/25516660/647ed564-2c1e-11e7-8e4e-6bc2841777fc.png)
(I changed that to **public**)

**Comment by helospark** [comment]
There should be a static builder method in the generated class.
It should be used like:
```java
Clazz result = Clazz.builder()
                     .withField1(...)
                     .withField2(...)
                     .build();
```

Currently `new Clazz.Builder()` usage is not supported (without static builder() method).

**Comment by ddsdggsg** [comment]
thank you   ; )
