### ISSUE TITLE
Add hashCode, equals and toString to plugin

### ISSUE THREAD

**Issue by shark300** [helospark/SparkBuilderGenerator#15]
It's nice to generate equals, toString and hashCode to the generated classes.

**Comment by helospark** [comment]
Builder classes are temporary objects used to help in the creation of (immutable) domain objects. It should be used like:
```
Clazz result = Clazz.builder()
   .withField1()
   .withField2()
   .build()
```
I cannot see any usecase where builders would have to be compared, placed into maps or printed.
Of course the generated class could (and should) have equals/hashCode/toString method, but that is not the responsibility of this plugin to generate.

_I'll close this, but if you really need this feature, feel free to open a pull request_

**Comment by rpofuk** [comment]
Nothis would be usefull but not for builder, but for class builder is generated for.

**Comment by helospark** [comment]
@rpofuk Eclipse already have build-in function to generate equals and hashCode.
Source (ctrl+shift+s)->Generate hashCode() and equals()
