### ISSUE TITLE
Doesn't show up on eclipse neon

### ISSUE THREAD

**Issue by trallarn** [helospark/SparkBuilderGenerator#19]
The menu item for generating a builder is missing and there is no spark-configuration under Preferences. It feels like eclipse isn't picking up the plugin.

Eclipse does however show the plugin under installed software:

<img width="1165" alt="screen shot 2017-09-21 at 11 59 31" src="https://user-images.githubusercontent.com/535469/30690398-63a5f474-9ec4-11e7-8406-5f319a5a90d2.png">

I'm running eclipse installed with the eclipse installer:
Version: Neon.3 Release (4.6.3)
Build id: 20170314-1500

Any ideas on what's wrong?

**Comment by helospark** [comment]
Hi @trallarn,

My first guess would be, that this is the same issue as:
https://github.com/helospark/SparkBuilderGenerator/issues/17
(permission issue and a bug in Eclipse causes all plugins to not be able to install properly)

Please check, if this applies to you.

**Comment by trallarn** [comment]
Hi @helospark, 

I've checked my logs but no such errors. I just reinstalled the plugin to see if something occurs during installation but no. There are no logged errors that I can find. 

Running om mac btw, #17 seemed to be a windows-issue.

**Comment by helospark** [comment]
I think it is not a Windows only issue, but occurs if the plugin jar files cannot be saved for whatever reason while the workspace is writable, in that case Eclipse successfully finishes the install, but there are not runnable jar file to actually start the plugin. 
Can you check if the jar file has been downloaded and not currupt (openable as a zip).
On MAC the jar should be:
 - ~/p2/pool/plugins/com.helospark.SparkBuilderGenerator_0.0.10.201704081131.jar
And is there a feature.xml in:
 - ~/p2/pool/features/com.helospark.SparkBuilderGeneratorFeature_0.0.10.201704081131

_It is in the home directory of the user who installed the plugin._

_md5sum com.helospark.SparkBuilderGenerator_0.0.10.201704081131.jar:
a22f3ba546e0633d78f40ab15005eb6c  com.helospark.SparkBuilderGenerator_0.0.10.201704081131.jar_

Do you not see any error in the error log, or just nothing related to the plugin? - Usually there are at least some minor error messages and warnings there, you could also check the log file manually in you workspace_folder/.metadata/.log, in case Eclipse did not read it for some reason.
Do you see anything new in here?

Also what Java version are you using to run Eclipse? - this plugin requires at least 1.8

**Comment by trallarn** [comment]
md5 sum verified 
the jar is extractable and readable by all
the feature.xml is readable by all

java version "1.8.0_131"

I did find this error in the log:
"Caused by: com.jniwrapper.LibraryNotFoundException: Cannot find JNIWrapper native library (libjniwrap.jnilib) in java.library.path:" <......>

and I've added the missing file to java.library.path so no more exception but still no spark-plugin.

I've run eclipse with flags like -initialize -clean but to no avail.

I have lots of other plugins working correctly so it's not a general problem with plugin loading.
Do you know if there is any log of what plugins are loaded by eclipse?

**Comment by helospark** [comment]
Hmm, strange, I'm starting to run out of ideas.

I have tried the exact Eclipse Neon build you have with a fresh install on Windows and Linux, and the plugin installed and started on both without problem.

Unfortunately I don't have a MAC (neither my friends), but I'll try to get one to try it on.
I'll get back to you after testing it on MAC.

**Comment by helospark** [comment]
Hey @trallarn,

I have tested on MacOSX Sierra (10.12) and the plugin successfully lunches with a fresh Eclipse for Java EE developers installation:
![sparkbuilder_macos](https://user-images.githubusercontent.com/14263031/30822341-b00c77cc-a228-11e7-8f79-c7ca6753f65a.png)

Based on the following StackOverflow answer, you may be able to get some diagnostic information: https://stackoverflow.com/a/7777020/8258222
Basically open OSGI console (console -> openConsole tab -> dropdown -> Host OSGI console), and run:
`ss SparkBuilderGenerator`
then get the id of the result and run:
`diag id`
and 
`bundle id`
I hope it should show some diagnostic information (ex. missing dependency), based on which we could start to find out, why it does not start.

Please run the above commands, and let me know if there is anything interesting in the result.

Also just a couple of more questions :)
 - Have you also tested on a fresh install?
 - Have you check tried installing it via "dropin folder"?

**Comment by trallarn** [comment]
Hi @helospark.

Thanks for testing on mac. I have now tried on a fresh eclipse install and the plugin works there so I guess there might be a conflicting plugin that prevents the installation on my normal eclipse installation.

There are no hits when I run:
ss SparkBuilderGenerator

Installing via dropin doesn't work either. 

So some kind of conflict with some other plugin I guess. I will see if I get time to find out which one.

**Comment by helospark** [comment]
Hello @trallarn,

I will close this issue, since I cannot repro it and everything points to an issue with some Eclipse plugin management.
If you find any new information that suggest that the builder generator is conflicting with another plugin please reopen/open a new issue.

Thanks for reporting it though.
