### ISSUE TITLE
Inheritance of class with full constructor does not work

### ISSUE THREAD

**Issue by martinariehm** [helospark/SparkBuilderGenerator#30]
See attached code. In case of inheritance, the complete constructor of base class is not called. TestChild shows the generated code, TestChildCorrect shows the code without compile errors. In addition, the builder functionality for the field a of the parent class is not generated. If the field is public, it is generated, but not working since the constructor is not called.
[inheritance.zip](https://github.com/helospark/SparkBuilderGenerator/files/1568573/inheritance.zip)

**Comment by helospark** [comment]
Thanks for reporting.

## AC
 - Find one visible constructor in the superclass, ignore if not found
 - Based on parameter names add these as fields to the builder
 - Generate super call for these in the private constructor

## Considerations

:question: Which constructor to select in case of multiple constructor?
:white_check_mark: Configurable, either the largest or empty

:question: Investigate the super constructor body, to check that the constructor parameter is the same as the method parameter name?
:white_check_mark: No, go with convention.

:question: Same visible parameter in the super class as in the constructor?
:white_check_mark: Use only constructor

## In scope:
:white_check_mark: Regular builder generator
:white_check_mark: Staged builder generator

## Configuration
:white_check_mark: Turn off this feature entirely for backward compatibility
:white_check_mark: Prefer empty super constructor or prefer largest constructor

**Comment by helospark** [comment]
Hey @martinariehm,

This change is available in version **0.0.13**.
Please update and check if everything is working as expected.

**Comment by martinariehm** [comment]
Updated and it works. Thanks a lot!
