### ISSUE TITLE
Instantiating the object using a private constructor breaks the JPA mapping

### ISSUE THREAD

**Issue by mailkatta** [helospark/SparkBuilderGenerator#39]
The builder generates a private constructor with the builder as the constructor argument. If the class has no default constructor defined, then JPA complains saying "No default constructor for entity". Is it possible to generate a default constructor in this case, if there is none present.

**Comment by helospark** [comment]
Hi @mailkatta,
Thanks for opening the ticket, I'll look into this when I have some time.

**Comment by helospark** [comment]
Hi @mailkatta,
I have released this change in **0.0.17**.

Note that this is not enabled by default, either you can enable it in the preferenes using option "Create public default constructor (ex. for JPA)" to generate empty constructor for all builders, or enable "Show dialog for regular builder" to generate it case-by-case basis.

Please update and try if it works as you expect.

**Comment by mailkatta** [comment]
Thanks for the prompt response.  This works as expected now. :+1:
