### ISSUE TITLE
Error with Eclipse 4.9.0 and Java 8

### ISSUE THREAD

**Issue by scotshall** [helospark/SparkBuilderGenerator#44]
Greetings,

I'm getting the following error when attempting to generate code in Eclipse v2018-09 (4.9.0) on Java 8:

java.lang.ClassCastException: org.eclipse.jdt.core.dom.EnumDeclaration cannot be cast to org.eclipse.jdt.core.dom.TypeDeclaration
org.eclipse.jdt.core.dom.EnumDeclaration cannot be cast to org.eclipse.jdt.core.dom.TypeDeclaration
  com.helospark.spark.builder.handlers.codegenerator.BuilderOwnerClassFinder.getFirstType(BuilderOwnerClassFinder.java:128)
  com.helospark.spark.builder.handlers.codegenerator.BuilderOwnerClassFinder.getBuilderOwnerType(BuilderOwnerClassFinder.java:62)
  com.helospark.spark.builder.handlers.codegenerator.BuilderOwnerClassFinder.provideBuilderOwnerClass(BuilderOwnerClassFinder.java:44)
  com.helospark.spark.builder.handlers.GenerateBuilderExecutorImpl.addBuilder(GenerateBuilderExecutorImpl.java:62)
  com.helospark.spark.builder.handlers.GenerateBuilderExecutorImpl.execute(GenerateBuilderExecutorImpl.java:51)
  com.helospark.spark.builder.handlers.GenerateBuilderHandlerErrorHandlerDecorator.execute(GenerateBuilderHandlerErrorHandlerDecorator.java:25)
  com.helospark.spark.builder.handlers.StateInitializerGenerateBuilderExecutorDecorator.execute(StateInitializerGenerateBuilderExecutorDecorator.java:26)
  com.helospark.spark.builder.handlers.GenerateDefaultBuilderHandler.execute(GenerateDefaultBuilderHandler.java:33)
  org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:294)
  org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:96)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
  org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:320)
  org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:254)
  org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:164)
  org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
  org.eclipse.core.commands.Command.executeWithChecks(Command.java:497)
  org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:490)
  org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:207)
  org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:436)
  org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
  org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
  org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
  org.eclipse.swt.widgets.Display.sendEvent(Display.java:4145)
  org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
  org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3958)
  org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3561)
  org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
  org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
  org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
  org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
  org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:628)
  org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
  org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
  org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
  org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
  org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:199)
  org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
  org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
  org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:391)
  org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:246)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
  org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
  org.eclipse.equinox.launcher.Main.run(Main.java:1501)

**Comment by helospark** [comment]
Hi @scotshall,
Thank you for reporting this.
Based on the stacktrace it is caused by having an enum as the first type in you java file, where you are trying to generate a builder and improper class checking in the builder generator tool before casting.

I'll improve the type checking when I have some time (hopefully tomorrow).

**Comment by scotshall** [comment]
You're right.  Never occurred to me to check the type.  Thanks for the quick response.

**Comment by helospark** [comment]
`0.0.19` release contains the fix for this issue.
