### ISSUE TITLE
Doesn't seem to work on Eclipse 4.9

### ISSUE THREAD

**Issue by rickdong** [helospark/SparkBuilderGenerator#48]
Running on Eclipse 4.9 on a Mac, there appears to be no button on the toolbar as well as the preference panel under Window->Preferences->Java->Spark Builder Generator.

Version: 2018-09 (4.9.0)
Build id: 20180917-1800

**Comment by helospark** [comment]
Thanks for reporting this issue @rickdong , however I'm not able to repro it, as I'm also using it under 4.9.0 and it works fine.
There were a few similar issues: #17 and #19, most likely it is an issue with the plugin installation rather then the plugin itself.
One common issue for this in Eclipse is that you do not have permission to write to the folder where plugins are installed. Are other plugins installing fine?
Do you see any errors in the error log (Window->Show view->Error log)?
Does the plugin show up in Help->About->Installation details -> plugins?

**Comment by zsalab** [comment]
I do have the same problem, the preferences are fine, but no icon and the key combo also does not work. I am running Eclipse 4.10 on MacOS (Java 8)

**Comment by helospark** [comment]
Hi @zsalab ,
Do you see anything related in the error log (Window->Show view->Error log).
Does anything happen if you use the hotkey: `command+shift+b`?
Do you have the latest version installed and were there any errors during installation?

**Comment by zsalab** [comment]
with command+shift+b works well, but the icon does not show up and I do not see related message in the error log

**Comment by helospark** [comment]
@zsalab Has the icon showed up previously?
Have you done customization on the toolbar? (If you can, could you share a screenshot?)

**Comment by rickdong** [comment]
Just to update on the original issue. A fresh install of Eclipse followed by the plugin installation did make the issue went away, so I think the issue is related to existing workspace metafile.
