### ISSUE TITLE
public Constructor for Builder Class for mandatory Fields

### ISSUE THREAD

**Issue by sl4ng3r** [helospark/SparkBuilderGenerator#49]
Hi, 
first of all, thanks for your Plugin. I really love it and thanks 4 your work. 

Actually my code has a lot of parameters to deal with and some of them are mandatory. It would be really great, if I could choose, witch value (for the normal Builder -- not stage) is mandatory. 

A Class generated like this would be great (expect the main Method ;-)) -->

`public class BuilderTest {

	private String value1;
	private String value2;
	private String value3;

	private BuilderTest(Builder builder) {
		this.value1 = builder.value1;
		this.value2 = builder.value2;
		this.value3 = builder.value3;
	}
	
	public String getValue1() {
		return value1;
	}
	public void setValue1(String value1) {
		this.value1 = value1;
	}
	public String getValue2() {
		return value2;
	}
	public void setValue2(String value2) {
		this.value2 = value2;
	}
	public String getValue3() {
		return value3;
	}
	public void setValue3(String value3) {
		this.value3 = value3;
	}

	
	/**
	 * Builder to build {@link BuilderTest}.
	 */
	public static final class Builder {
		private String value1;
		private String value2;
		private String value3;

		public Builder(String value1) {
			this.value1 = value1;
		}

		public Builder withValue2(String value2) {
			this.value2 = value2;
			return this;
		}

		public Builder withValue3(String value3) {
			this.value3 = value3;
			return this;
		}

		public BuilderTest build() {
			return new BuilderTest(this);
		}
	}
	
	
	public static void main(String[] args) {
		BuilderTest bt = new BuilderTest.Builder("MyValue1").withValue2("MyValue2").build();
	}
	
	
}`

In this example, the value1 variable is mandatory, so i have to put it in the Builder constructor. 

This feature would be verry nice 👍 

Friendly Regards

Alex

**Comment by helospark** [comment]
Hi Alex,

Thank you for your detailed issue, your proposal seems useful.
I'll get on it when my time allows.

**Comment by helospark** [comment]
Hey @sl4ng3r ,

Please update to 0.0.21 and try if it works as expected.

You need to enable `Show options dialog before every builder generation` in the preferences under Regular builder settings.
And either select on the preferences or on the dialog `Create public builder constructor with mandatory fields`, then you can select which fields are mandatory.

![screenshot at 2018-12-17 15-34-55](https://user-images.githubusercontent.com/14263031/50093606-6f81fc00-0211-11e9-9ad8-fe5236b3d140.png)

**Comment by sl4ng3r** [comment]
Thank you verry much :-) it works nice. 
Think about to change your version shown in the marketplace ;-)
Friendly Regards
Alex
![2018-12-17 16_05_07-greenshot](https://user-images.githubusercontent.com/16105017/50095354-abb75b80-0215-11e9-8ea9-b621e5fe0635.jpg)
