### ISSUE TITLE
Error para descargar sparkbuilder

### ISSUE THREAD

**Issue by CoralineSanz** [helospark/SparkBuilderGenerator#56]
I cannot use spakbuilder
java.lang.NoSuchMethodError: org.eclipse.jdt.core.IType.getClassFile()Lorg/eclipse/jdt/core/IOrdinaryClassFile;
org.eclipse.jdt.core.IType.getClassFile()Lorg/eclipse/jdt/core/IOrdinaryClassFile;
  com.helospark.spark.builder.handlers.codegenerator.component.helper.TypeDeclarationFromSuperclassExtractor.getCompilationUnit(TypeDeclarationFromSuperclassExtractor.java:65)
  com.helospark.spark.builder.handlers.codegenerator.component.helper.TypeDeclarationFromSuperclassExtractor.extractTypeDeclaration(TypeDeclarationFromSuperclassExtractor.java:45)
  com.helospark.spark.builder.handlers.codegenerator.component.helper.TypeDeclarationFromSuperclassExtractor.lambda$0(TypeDeclarationFromSuperclassExtractor.java:37)
  java.util.Optional.flatMap(Unknown Source)
  com.helospark.spark.builder.handlers.codegenerator.component.helper.TypeDeclarationFromSuperclassExtractor.extractTypeDeclarationFromSuperClass(TypeDeclarationFromSuperclassExtractor.java:37)
  com.helospark.spark.builder.handlers.codegenerator.builderfieldcollector.SuperConstructorParameterCollector.collect(SuperConstructorParameterCollector.java:46)
  com.helospark.spark.builder.handlers.codegenerator.ApplicableBuilderFieldExtractor.lambda$0(ApplicableBuilderFieldExtractor.java:28)
  java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
  java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
  com.helospark.spark.builder.handlers.codegenerator.ApplicableBuilderFieldExtractor.findBuilderFields(ApplicableBuilderFieldExtractor.java:27)
  com.helospark.spark.builder.handlers.codegenerator.RegularBuilderCompilationUnitGeneratorBuilderFieldCollectingDecorator.generateBuilder(RegularBuilderCompilationUnitGeneratorBuilderFieldCollectingDecorator.java:35)
  com.helospark.spark.builder.handlers.GenerateBuilderExecutorImpl.addBuilder(GenerateBuilderExecutorImpl.java:68)
  com.helospark.spark.builder.handlers.GenerateBuilderExecutorImpl.execute(GenerateBuilderExecutorImpl.java:51)
  com.helospark.spark.builder.handlers.GenerateBuilderHandlerErrorHandlerDecorator.execute(GenerateBuilderHandlerErrorHandlerDecorator.java:25)
  com.helospark.spark.builder.handlers.StateInitializerGenerateBuilderExecutorDecorator.execute(StateInitializerGenerateBuilderExecutorDecorator.java:26)
  com.helospark.spark.builder.handlers.GenerateDefaultBuilderHandler.execute(GenerateDefaultBuilderHandler.java:33)
  org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
  org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
  org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
  org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
  org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
  org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
  org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
  org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
  org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
  org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:431)
  org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:446)
  org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:472)
  org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
  org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
  org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
  org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
  org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
  org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
  org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
  org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
  org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
  org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
  org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
  org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
  org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
  org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
  org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
  org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
  org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
  org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
  org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
  org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
  org.eclipse.equinox.launcher.Main.run(Main.java:1499)
![isue](https://user-images.githubusercontent.com/84336854/125073603-d7bfb400-e081-11eb-8a7e-d34013ab155c.JPG)

**Comment by helospark** [comment]
Which Eclipse version do you use?
This method should exist since JDT version 3.14 (Eclipse Photon)

**Comment by helospark** [comment]
Closed due to inactivity.
Reopen if needed with the above info provided.
