### ISSUE TITLE
Does not work if class extends from another (abstract) class

### ISSUE THREAD

**Issue by nigzak** [helospark/SparkBuilderGenerator#62]
the build in sparktool fails if your class extends another class

ex:

abstract class A {
     private int x;
}

class B extends A {
    private int y;
    // set the CURSOR HERE to add builder
}

click on "build" icon => error

java.lang.IllegalArgumentException
java.lang.IllegalArgumentException
  org.eclipse.jdt.core.dom.ASTNode.checkNewChild(ASTNode.java:2552)
  org.eclipse.jdt.core.dom.ASTNode.preReplaceChild(ASTNode.java:2618)
  org.eclipse.jdt.core.dom.VariableDeclaration.setInitializer(VariableDeclaration.java:360)
  com.helospark.spark.builder.handlers.codegenerator.component.fragment.builderclass.field.FieldDeclarationPostProcessor.postProcessFragment(FieldDeclarationPostProcessor.java:42)
  com.helospark.spark.builder.handlers.codegenerator.component.fragment.builderclass.field.BuilderFieldAdderFragment.createFieldDeclarationFragment(BuilderFieldAdderFragment.java:42)
  com.helospark.spark.builder.handlers.codegenerator.component.fragment.builderclass.field.BuilderFieldAdderFragment.addFieldToBuilder(BuilderFieldAdderFragment.java:33)
  com.helospark.spark.builder.handlers.codegenerator.component.RegularBuilderClassCreator.createBuilderClass(RegularBuilderClassCreator.java:68)
  com.helospark.spark.builder.handlers.codegenerator.RegularBuilderCompilationUnitGenerator.generateBuilder(RegularBuilderCompilationUnitGenerator.java:58)
  com.helospark.spark.builder.handlers.codegenerator.RegularBuilderCompilationUnitGeneratorBuilderFieldCollectingDecorator.lambda$0(RegularBuilderCompilationUnitGeneratorBuilderFieldCollectingDecorator.java:37)
  java.base/java.util.Optional.ifPresent(Optional.java:178)
  com.helospark.spark.builder.handlers.codegenerator.RegularBuilderCompilationUnitGeneratorBuilderFieldCollectingDecorator.generateBuilder(RegularBuilderCompilationUnitGeneratorBuilderFieldCollectingDecorator.java:37)
  com.helospark.spark.builder.handlers.GenerateBuilderExecutorImpl.addBuilder(GenerateBuilderExecutorImpl.java:68)
  com.helospark.spark.builder.handlers.GenerateBuilderExecutorImpl.execute(GenerateBuilderExecutorImpl.java:51)
  com.helospark.spark.builder.handlers.GenerateBuilderHandlerErrorHandlerDecorator.execute(GenerateBuilderHandlerErrorHandlerDecorator.java:25)
  com.helospark.spark.builder.handlers.StateInitializerGenerateBuilderExecutorDecorator.execute(StateInitializerGenerateBuilderExecutorDecorator.java:26)
  com.helospark.spark.builder.handlers.GenerateDefaultBuilderHandler.execute(GenerateDefaultBuilderHandler.java:33)
  org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
  org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
  jdk.internal.reflect.GeneratedMethodAccessor102.invoke(Unknown Source)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:568)
  org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
  org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:317)
  org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:251)
  org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
  org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
  org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
  org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:485)
  org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
  org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:438)
  org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:449)
  org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:475)
  org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
  org.eclipse.swt.widgets.Display.sendEvent(Display.java:4251)
  org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
  org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4068)
  org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3645)
  org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
  org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
  org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
  org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
  org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
  org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
  org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
  org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
  org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
  org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
  org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
  org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
  org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
  org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:568)
  org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
  org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
  org.eclipse.equinox.launcher.Main.run(Main.java:1467)

**Comment by helospark** [comment]
Hello @nigzak !
This works for me.
Are you using the latest plugin version?
And which version of Eclipse do you use?

**Comment by helospark** [comment]
If you switch of `Initialize builder field with default value from the owner class` in the preferences, does the issue disappear?

**Comment by helospark** [comment]
I was not able to repro with your example, but using field initialization in superclass with the above option enabled caused the same exception.
I have made the fix in #63

**Comment by helospark** [comment]
I have released 0.0.25 containing the fix, please check.

**Comment by nigzak** [comment]
Hi
sorry .. I did not expect you are that fast ... super :)
It seems that I have (sadly) put a bad example - but nevertheless it works now without any issue.

shame on my head ... I will in future check better that it I find something bad the examples are really better ... sorry for this ... 

Again: thank you! 2h from "find something" (without good example ...) to fix ... can only say wow for this timing ;)
